#ifndef TIETOKANTADLL_GLOBAL_H
#define TIETOKANTADLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TIETOKANTADLL_LIBRARY)
#  define TIETOKANTADLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TIETOKANTADLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TIETOKANTADLL_GLOBAL_H
